name: Convert HTML to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: install japanese fonts
      run: sudo apt-get install -y fonts-ipafont-gothic

    - name: Install Cheerio
      run: npm install cheerio
    
    - name: Extract Title
      id: extract
      run: |
        TITLE=$(
        node -e "
          const fs = require('fs');
          const cheerio = require('cheerio');
          const html = fs.readFileSync('${{ github.workspace }}/index.html', 'utf-8');
          const $ = cheerio.load(html);
          const titleHtml = $.html('head title');
          const titleText = cheerio.load(titleHtml)('title').text();
        ")
        echo "PDF_TITLE=${TITLE// /_}" >> $GITHUB_ENV
    
    - name: Convert HTML to PDF
      run: "node -e \"
        const puppeteer = require('puppeteer');
        (
          async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto('file://${{ github.workspace }}/index.html', {waitUntil: 'networkidle2'});
            await page.pdf({path: '${{ env.PDF_TITLE}}.pdf', format: 'A4'});
            await browser.close();
          }
        )();\""
    
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PDF_TITLE}}
        path: ${{ env.PDF_TITLE}}.pdf






